# GENERATED by scripts/generate_market_calendar.py — do not edit.
# Source of truth: scripts/market_calendar/ and config/market-calendar-dependency.yaml.
"""Generated contract tests for the vendored exchange calendar."""

from datetime import date, datetime
from zoneinfo import ZoneInfo

import _market_calendar as calendar
import pytest


def test_supported_cash_equity_venues():
    assert calendar.supported_venues() == ("XLON", "XNAS", "XNYS", "XTKS")


def test_jpx_close_cutover_and_lunch_break():
    before = calendar.session_for_date("XTKS", date(2024, 11, 1))
    after = calendar.session_for_date("XTKS", date(2024, 11, 5))
    assert before.market_close.strftime("%H:%M") == "15:00"
    assert after.market_close.strftime("%H:%M") == "15:30"
    assert after.break_start.strftime("%H:%M") == "11:30"
    assert after.break_end.strftime("%H:%M") == "12:30"
    assert (
        calendar.is_open_at("XTKS", datetime(2024, 11, 5, 12, 0, tzinfo=ZoneInfo("Asia/Tokyo")))
        is False
    )


def test_us_holiday_early_close_and_dst():
    assert calendar.session_for_date("XNYS", date(2026, 4, 3)) is None
    early = calendar.session_for_date("XNYS", date(2026, 11, 27))
    assert early.market_close.strftime("%H:%M %z") == "13:00 -0500"
    winter = calendar.session_for_date("XNYS", date(2026, 1, 5))
    summer = calendar.session_for_date("XNAS", date(2026, 7, 6))
    assert winter.market_open.utcoffset().total_seconds() == -5 * 3600
    assert summer.market_open.utcoffset().total_seconds() == -4 * 3600


def test_lse_uses_dst_aware_timezone():
    winter = calendar.session_for_date("XLON", date(2026, 1, 5))
    summer = calendar.session_for_date("XLON", date(2026, 7, 6))
    assert winter.market_open.tzname() == "GMT"
    assert summer.market_open.tzname() == "BST"


def test_next_session_skips_weekend_and_holiday():
    session = calendar.next_session_on_or_after("XNYS", date(2026, 7, 3))
    assert session.session_date == date(2026, 7, 6)
    later = calendar.next_session_after("XNYS", date(2026, 7, 6))
    assert later.session_date == date(2026, 7, 7)


def test_previous_session_skips_weekend_and_holiday():
    session = calendar.previous_session_before("XNYS", date(2026, 7, 6))
    assert session.session_date == date(2026, 7, 2)
    same = calendar.previous_session_on_or_before("XNYS", date(2026, 7, 6))
    assert same.session_date == date(2026, 7, 6)


@pytest.mark.parametrize(
    ("include_start", "include_end", "expected"),
    [(False, False, 0), (False, True, 1), (True, False, 1), (True, True, 2)],
)
def test_count_session_boundaries(include_start, include_end, expected):
    assert (
        calendar.count_sessions(
            "XNYS",
            date(2026, 7, 2),
            date(2026, 7, 6),
            include_start=include_start,
            include_end=include_end,
        )
        == expected
    )


def test_same_day_and_reverse_contracts():
    assert (
        calendar.count_sessions(
            "XNYS",
            date(2026, 7, 6),
            date(2026, 7, 6),
            include_start=True,
            include_end=True,
        )
        == 1
    )
    with pytest.raises(ValueError, match="on or before"):
        calendar.count_sessions(
            "XNYS",
            date(2026, 7, 7),
            date(2026, 7, 6),
            include_start=False,
            include_end=True,
        )


def test_naive_datetime_and_unknown_venue_fail_closed():
    with pytest.raises(ValueError, match="timezone-aware"):
        calendar.is_open_at("XNYS", datetime(2026, 7, 6, 10, 0))
    with pytest.raises(ValueError, match="Unsupported venue"):
        calendar.session_for_date("NOPE", date(2026, 7, 6))


def test_parse_aware_datetime_accepts_z_and_rejects_date_only():
    parsed = calendar.parse_aware_datetime("2026-07-06T14:00:00Z")
    assert parsed.utcoffset().total_seconds() == 0
    with pytest.raises(ValueError, match="timezone-aware"):
        calendar.parse_aware_datetime("2026-07-06")


def test_close_is_exclusive_and_current_session_rolls_forward():
    at_close = datetime(2026, 11, 27, 13, 0, tzinfo=ZoneInfo("America/New_York"))
    assert calendar.is_open_at("XNYS", at_close) is False
    assert calendar.current_or_next_session("XNYS", at_close).session_date == date(2026, 11, 30)


def test_provider_failure_is_not_treated_as_a_holiday(monkeypatch):
    def fail_provider(_venue):
        raise calendar.CalendarUnavailableError("calendar unavailable")

    monkeypatch.setattr(calendar, "_provider_calendar", fail_provider)
    with pytest.raises(calendar.CalendarUnavailableError, match="unavailable"):
        calendar.session_for_date("XNYS", date(2026, 7, 6))


def test_search_horizon_failure_is_explicit(monkeypatch):
    class EmptySchedule:
        empty = True

    monkeypatch.setattr(
        calendar,
        "_schedule",
        lambda venue, start, end: ("XNYS", "America/New_York", EmptySchedule()),
    )
    with pytest.raises(calendar.CalendarUnavailableError, match="No XNYS session"):
        calendar.next_session_on_or_after("XNYS", date(2026, 7, 6), max_search_days=1)
