#!/usr/bin/env python3
# GENERATED by scripts/generate_fmp_client.py — do not edit.
# Source of truth: scripts/fmp_client/specials/ and scripts/fmp_client/registry.py.
# Regenerate: python3 scripts/generate_fmp_client.py
"""FMP client for the Claude Code-native US GARP screening pipeline.

This module deliberately keeps bulk provider payloads out of the language-model
context. Successful responses are cached in SQLite and may be mirrored to a raw
artifact directory; callers receive Python objects and should emit only compact
summaries to stdout.

The implementation follows the repository's existing FMP conventions:
- FMP_API_KEY from the environment or constructor
- stable endpoints first, legacy v3 fallback where available
- request pacing, 429 retry, endpoint circuit breaking, and call budgeting
- deterministic diagnostics without exposing the API key
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sqlite3
import sys
import time
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests", file=sys.stderr)
    raise

# Mirror of scripts/provider_contracts.py::redact_url (clients are standalone).
# Requires a `?`/`&` prefix, so this masks apikey=/api_key= in URL query
# strings, not a rendered params dict (unreachable today: only
# RequestException text -- which can embed the full request URL -- is
# ever printed here, never a bare params repr()).
_APIKEY_RE = re.compile(r"([?&](?:apikey|api_key)=)[^&\s]+", re.IGNORECASE)


def _redact_key(text: str) -> str:
    """Mask apikey=/api_key= query values so stderr never carries the key."""
    return _APIKEY_RE.sub(r"\1REDACTED", str(text))


_PROVIDER_ERROR_KEYS = frozenset({"error message", "errormessage", "error"})


def _is_provider_error_payload(payload: Any) -> bool:
    """True for HTTP-200 error objects (e.g. {"Error Message": "plan limit"})."""
    if not isinstance(payload, dict):
        return False
    keys = {str(key).strip().lower() for key in payload}
    return bool(keys & _PROVIDER_ERROR_KEYS)


def _finite_number(value: Any) -> bool:
    if isinstance(value, bool) or value is None:
        return False
    try:
        number = float(value)
    except (TypeError, ValueError):
        return False
    return number == number and number not in (float("inf"), float("-inf"))


# Exactly the estimate-value fields the normalizer consumes (its _pick key
# lists, lowercased). Substring matching is NOT allowed here: numAnalystsEps
# contains "eps" but is a count, never an estimate value.
_ESTIMATE_VALUE_KEYS = frozenset(
    {
        "epsavg",
        "eps_avg",
        "eps",
        "estimated_eps",
        "epslow",
        "eps_low",
        "epshigh",
        "eps_high",
        "revenueavg",
        "revenue_avg",
        "revenue",
        "estimated_revenue",
    }
)


def _parseable_estimate_date(value: Any) -> bool:
    """Full-string ISO parse, the same rule the normalizer applies.

    Truncating to ten characters let ``2026-12-31garbage`` through; the
    WHOLE string must parse.
    """
    text = str(value or "").strip()
    if not text:
        return False
    try:
        datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return False
    return True


def _valid_estimates_payload(payload: Any) -> bool:
    """Schema gate for analyst-estimates payloads (pre-cache AND on cache read).

    A genuinely empty list is valid (no consensus). Anything else must be a
    list of mappings that are not provider error objects, whose date parses
    IN FULL under the normalizer's rule, and that hold a FINITE number in at
    least one field the normalizer actually consumes —
    ``[{"Error Message": ...}]`` is an outage,
    ``[{"date": "2026-12-31garbage", ...}]`` and rows whose only "value" is
    an analyst count are unusable noise; none may complete a symbol as
    "no estimates".
    """
    if payload == []:
        return True
    if not isinstance(payload, list):
        return False
    for row in payload:
        if not isinstance(row, dict) or _is_provider_error_payload(row):
            return False
        if not _parseable_estimate_date(row.get("date")):
            return False
        has_finite_estimate = any(
            str(key).strip().lower() in _ESTIMATE_VALUE_KEYS and _finite_number(value)
            for key, value in row.items()
        )
        if not has_finite_estimate:
            return False
    return True


class ApiCallBudgetExceeded(RuntimeError):
    """Raised when the configured provider-call ceiling is reached."""


class FMPResponseError(RuntimeError):
    """Raised for malformed or unusable provider responses in strict mode."""


@dataclass(frozen=True)
class CachePolicy:
    default_ttl_seconds: int = 86_400
    quote_ttl_seconds: int = 3_600
    historical_ttl_seconds: int = 86_400
    estimates_ttl_seconds: int = 259_200
    statements_ttl_seconds: int = 604_800
    universe_ttl_seconds: int = 604_800


class SQLiteJsonCache:
    """Small persistent JSON cache keyed by URL and non-secret parameters."""

    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._connection = sqlite3.connect(self.path)
        self._connection.execute(
            """
            CREATE TABLE IF NOT EXISTS responses (
                cache_key TEXT PRIMARY KEY,
                created_at REAL NOT NULL,
                payload TEXT NOT NULL
            )
            """
        )
        self._connection.commit()

    @staticmethod
    def make_key(url: str, params: Mapping[str, Any]) -> str:
        clean = {
            str(k): v for k, v in params.items() if str(k).lower() not in {"apikey", "api_key"}
        }
        encoded = json.dumps(
            [url, clean], ensure_ascii=False, sort_keys=True, separators=(",", ":")
        )
        return hashlib.sha256(encoded.encode("utf-8")).hexdigest()

    def get_entry(self, key: str, ttl_seconds: int) -> tuple[Any, float] | None:
        """Return (payload, created_at) for a fresh entry, else None."""
        row = self._connection.execute(
            "SELECT created_at, payload FROM responses WHERE cache_key = ?", (key,)
        ).fetchone()
        if row is None:
            return None
        created_at, payload = row
        if ttl_seconds >= 0 and time.time() - float(created_at) > ttl_seconds:
            self.delete(key)
            return None
        try:
            return json.loads(payload), float(created_at)
        except json.JSONDecodeError:
            self.delete(key)
            return None

    def get(self, key: str, ttl_seconds: int) -> Any | None:
        entry = self.get_entry(key, ttl_seconds)
        return entry[0] if entry is not None else None

    def delete(self, key: str) -> None:
        self._connection.execute("DELETE FROM responses WHERE cache_key = ?", (key,))
        self._connection.commit()

    def put(self, key: str, payload: Any) -> None:
        text = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        self._connection.execute(
            "INSERT OR REPLACE INTO responses(cache_key, created_at, payload) VALUES(?, ?, ?)",
            (key, time.time(), text),
        )
        self._connection.commit()

    def close(self) -> None:
        self._connection.close()


class FMPClient:
    """Stable-first FMP client with persistent caching and compact diagnostics."""

    STABLE_URL = "https://financialmodelingprep.com/stable"
    V3_URL = "https://financialmodelingprep.com/api/v3"
    RATE_LIMIT_DELAY = 0.30
    ENDPOINT_FAILURE_THRESHOLD = 3
    CAPABILITY_CACHE_TTL_DAYS = 30
    CAPABILITY_DISABLING_STATUS_CODES = (402, 403)

    def __init__(
        self,
        api_key: str | None = None,
        *,
        max_api_calls: int = 500,
        cache_path: str | Path = ".cache/fmp/fmp-cache.sqlite3",
        raw_store_dir: str | Path | None = None,
        cache_policy: CachePolicy | None = None,
        offline: bool = False,
        timeout_seconds: int = 30,
        rate_limit_delay: float | None = None,
        respect_capability_cache: bool = True,
    ):
        self.api_key = api_key or os.getenv("FMP_API_KEY")
        self.offline = bool(offline)
        # Provenance of the payload returned by the most recent
        # _request_json call: {"source": "cache"|"http"|None,
        # "retrieved_at": epoch float|None}. Single-threaded CLI client.
        self._last_response_meta: dict[str, Any] = {"source": None, "retrieved_at": None}
        if not self.api_key and not self.offline:
            raise ValueError("FMP API key required. Set FMP_API_KEY or pass api_key.")
        self.max_api_calls = int(max_api_calls)
        if self.max_api_calls <= 0:
            raise ValueError("max_api_calls must be positive")
        self.timeout_seconds = int(timeout_seconds)
        self.rate_limit_delay = (
            self.RATE_LIMIT_DELAY if rate_limit_delay is None else max(0.0, float(rate_limit_delay))
        )
        self.cache_policy = cache_policy or CachePolicy()
        self.cache = SQLiteJsonCache(cache_path)
        self.raw_store_dir = Path(raw_store_dir) if raw_store_dir else None
        if self.raw_store_dir:
            self.raw_store_dir.mkdir(parents=True, exist_ok=True)
        self.session = requests.Session()
        self.last_call_time = 0.0
        self.api_calls_made = 0
        self.cache_hits = 0
        self.failures: list[dict[str, Any]] = []
        self._endpoint_failures: dict[str, int] = {}
        self._disabled_endpoints: set[str] = set()
        self.respect_capability_cache = bool(respect_capability_cache)
        self.capability_cache_hits = 0

    @property
    def remaining_calls(self) -> int:
        """API calls still available under the configured budget (never negative)."""
        return max(0, self.max_api_calls - self.api_calls_made)

    def __enter__(self) -> FMPClient:
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    def close(self) -> None:
        self.cache.close()
        self.session.close()

    @staticmethod
    def _safe_params(params: Mapping[str, Any]) -> dict[str, Any]:
        return {str(k): v for k, v in params.items() if str(k).lower() not in {"apikey", "api_key"}}

    def _write_raw(self, *, url: str, params: Mapping[str, Any], payload: Any) -> None:
        if self.raw_store_dir is None:
            return
        safe_params = self._safe_params(params)
        identity = json.dumps([url, safe_params], sort_keys=True, separators=(",", ":"))
        digest = hashlib.sha256(identity.encode("utf-8")).hexdigest()
        target = self.raw_store_dir / f"{digest}.json"
        wrapper = {
            "retrieved_at": datetime.now(timezone.utc).isoformat(),
            "url": url,
            "params": safe_params,
            "payload": payload,
        }
        temp = target.with_suffix(".tmp")
        temp.write_text(json.dumps(wrapper, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        os.replace(temp, target)

    def _record_failure(self, endpoint: str, reason: str, status_code: int | None = None) -> None:
        # `endpoint` is an identity key: the circuit breaker below and the
        # capability-cache gate in `_fetch_statements` compare it against the
        # raw url, so it is stored unredacted here and masked only where it
        # is exposed (`diagnostics()['failure_samples']`).
        item: dict[str, Any] = {"endpoint": endpoint, "reason": reason}
        if status_code is not None:
            item["status_code"] = status_code
        self.failures.append(item)
        count = self._endpoint_failures.get(endpoint, 0) + 1
        self._endpoint_failures[endpoint] = count
        if count >= self.ENDPOINT_FAILURE_THRESHOLD:
            self._disabled_endpoints.add(endpoint)

    def _request_json(
        self,
        url: str,
        params: Mapping[str, Any] | None = None,
        *,
        ttl_seconds: int | None = None,
        allow_empty: bool = False,
        quiet: bool = False,
        validate: Any | None = None,
    ) -> Any | None:
        request_params = dict(params or {})
        ttl = self.cache_policy.default_ttl_seconds if ttl_seconds is None else int(ttl_seconds)
        cache_key = SQLiteJsonCache.make_key(url, request_params)
        self._last_response_meta = {"source": None, "retrieved_at": None}
        entry = self.cache.get_entry(cache_key, ttl)
        if entry is not None:
            cached, created_at = entry
            if validate is not None and not validate(cached):
                # A payload cached before validation existed (or by another
                # tool) must not keep short-circuiting retries: purge it and
                # fall through to a fresh HTTP attempt.
                self._record_failure(url, "cached_payload_invalid")
                self.cache.delete(cache_key)
            else:
                self.cache_hits += 1
                self._last_response_meta = {"source": "cache", "retrieved_at": created_at}
                return cached
        if self.offline:
            return None
        if url in self._disabled_endpoints:
            return None
        if self.api_calls_made >= self.max_api_calls:
            raise ApiCallBudgetExceeded(
                f"FMP API call budget exhausted: {self.api_calls_made}/{self.max_api_calls}"
            )
        elapsed = time.time() - self.last_call_time
        if elapsed < self.rate_limit_delay:
            time.sleep(self.rate_limit_delay - elapsed)
        request_params["apikey"] = self.api_key
        attempts = 0
        while attempts < 2:
            if self.api_calls_made >= self.max_api_calls:
                raise ApiCallBudgetExceeded(
                    f"FMP API call budget exhausted: {self.api_calls_made}/{self.max_api_calls}"
                )
            attempts += 1
            try:
                response = self.session.get(
                    url, params=request_params, timeout=self.timeout_seconds
                )
                self.last_call_time = time.time()
                self.api_calls_made += 1
            except requests.RequestException as exc:
                self._record_failure(url, f"request_exception:{exc.__class__.__name__}")
                if not quiet:
                    print(
                        f"WARN: FMP request failed for {url}: {_redact_key(exc)}",
                        file=sys.stderr,
                    )
                return None
            if response.status_code == 429 and attempts < 2:
                time.sleep(60)
                continue
            if response.status_code != 200:
                self._record_failure(url, f"http_{response.status_code}", response.status_code)
                if not quiet:
                    print(
                        f"WARN: FMP endpoint failed: {_redact_key(url)} HTTP {response.status_code}",
                        file=sys.stderr,
                    )
                return None
            try:
                payload = response.json()
            except ValueError:
                self._record_failure(url, "invalid_json", response.status_code)
                if not quiet:
                    print(f"WARN: FMP returned invalid JSON: {_redact_key(url)}", file=sys.stderr)
                return None
            if _is_provider_error_payload(payload):
                # FMP reports plan limits and endpoint errors as HTTP 200
                # bodies like {"Error Message": "..."}; treating those as
                # data would cache the outage as an "empty" success.
                self._record_failure(url, "provider_error_payload", response.status_code)
                if not quiet:
                    print(
                        f"WARN: FMP returned an error payload: {_redact_key(url)}", file=sys.stderr
                    )
                return None
            if validate is not None and not validate(payload):
                # Same outage class hidden one level down (e.g. an error
                # object INSIDE a list) or a shape the endpoint never
                # produces: a failure, never cached.
                self._record_failure(url, "schema_validation_failed", response.status_code)
                if not quiet:
                    print(
                        f"WARN: FMP payload failed schema validation: {_redact_key(url)}",
                        file=sys.stderr,
                    )
                return None
            if not allow_empty and payload in (None, [], {}):
                self._record_failure(url, "empty_response", response.status_code)
                return None
            self._endpoint_failures[url] = 0
            self.cache.put(cache_key, payload)
            self._write_raw(url=url, params=request_params, payload=payload)
            self._last_response_meta = {"source": "http", "retrieved_at": time.time()}
            return payload
        self._record_failure(url, "rate_limit_exhausted", 429)
        return None

    def _stable_then_v3(
        self,
        stable_endpoint: str,
        stable_params: Mapping[str, Any],
        *,
        v3_endpoint: str | None = None,
        v3_params: Mapping[str, Any] | None = None,
        ttl_seconds: int | None = None,
        allow_empty: bool = False,
        validate: Any | None = None,
    ) -> Any | None:
        stable_url = f"{self.STABLE_URL}/{stable_endpoint.lstrip('/')}"
        data = self._request_json(
            stable_url,
            stable_params,
            ttl_seconds=ttl_seconds,
            allow_empty=allow_empty,
            quiet=v3_endpoint is not None,
            validate=validate,
        )
        if data is not None:
            return data
        if not v3_endpoint:
            return None
        v3_url = f"{self.V3_URL}/{v3_endpoint.lstrip('/')}"
        return self._request_json(
            v3_url,
            v3_params if v3_params is not None else stable_params,
            ttl_seconds=ttl_seconds,
            allow_empty=allow_empty,
            validate=validate,
        )

    def get_company_screener(
        self,
        *,
        exchange: str,
        min_market_cap: float,
        max_market_cap: float,
        min_price: float = 5.0,
        limit: int = 10_000,
    ) -> list[dict[str, Any]]:
        params = {
            "exchange": exchange,
            "marketCapMoreThan": int(min_market_cap),
            "marketCapLowerThan": int(max_market_cap),
            "priceMoreThan": float(min_price),
            "isEtf": "false",
            "isFund": "false",
            "isActivelyTrading": "true",
            "limit": int(limit),
        }
        data = self._stable_then_v3(
            "company-screener",
            params,
            v3_endpoint="stock-screener",
            v3_params=params,
            ttl_seconds=self.cache_policy.universe_ttl_seconds,
            allow_empty=True,
        )
        return [dict(row) for row in data] if isinstance(data, list) else []

    def get_quotes(self, symbols: Sequence[str], batch_size: int = 5) -> dict[str, dict[str, Any]]:
        result: dict[str, dict[str, Any]] = {}
        clean = [str(symbol).strip().upper() for symbol in symbols if str(symbol).strip()]
        for offset in range(0, len(clean), max(1, int(batch_size))):
            batch = clean[offset : offset + max(1, int(batch_size))]
            joined = ",".join(batch)
            data = self._stable_then_v3(
                "quote",
                {"symbol": joined},
                v3_endpoint=f"quote/{joined}",
                v3_params={},
                ttl_seconds=self.cache_policy.quote_ttl_seconds,
            )
            if isinstance(data, Mapping):
                data = [data]
            if isinstance(data, list):
                for row in data:
                    if isinstance(row, Mapping) and row.get("symbol"):
                        result[str(row["symbol"]).upper()] = dict(row)
        return result

    def get_historical_prices(
        self,
        symbol: str,
        *,
        from_date: str,
        to_date: str,
    ) -> list[dict[str, Any]]:
        data = self._stable_then_v3(
            "historical-price-eod/full",
            {"symbol": symbol, "from": from_date, "to": to_date},
            v3_endpoint=f"historical-price-full/{symbol}",
            v3_params={"from": from_date, "to": to_date},
            ttl_seconds=self.cache_policy.historical_ttl_seconds,
            allow_empty=True,
        )
        if isinstance(data, Mapping):
            data = data.get("historical") or data.get("historicalStockList") or []
        return [dict(row) for row in data] if isinstance(data, list) else []

    def get_analyst_estimates_detailed(
        self, symbol: str, *, period: str = "annual", limit: int = 6
    ) -> dict[str, Any]:
        """Structured estimates fetch tied to the ACTUALLY adopted response.

        Returns ``{"rows", "status", "served_from_cache", "retrieved_at"}``
        where status is ``ok`` (validated rows), ``empty`` (a genuine empty
        consensus from a successful response), or ``failed`` (any provider
        failure — HTTP error, offline miss, error payload, schema failure).
        ``retrieved_at`` is the epoch time the adopted payload was ACTUALLY
        fetched over HTTP (a cache hit keeps the cache entry's creation
        time); consumers must treat a missing value as unknown, never "now".
        """
        data = self._stable_then_v3(
            "analyst-estimates",
            {"symbol": symbol, "period": period, "limit": int(limit)},
            v3_endpoint=f"analyst-estimates/{symbol}",
            v3_params={"period": period, "limit": int(limit)},
            ttl_seconds=self.cache_policy.estimates_ttl_seconds,
            allow_empty=True,
            validate=_valid_estimates_payload,
        )
        if data is None:
            return {
                "rows": [],
                "status": "failed",
                "served_from_cache": False,
                "retrieved_at": None,
            }
        meta = dict(self._last_response_meta)
        rows = [dict(row) for row in data]
        return {
            "rows": rows,
            "status": "ok" if rows else "empty",
            "served_from_cache": meta.get("source") == "cache",
            "retrieved_at": meta.get("retrieved_at"),
        }

    def get_analyst_estimates(
        self, symbol: str, *, period: str = "annual", limit: int = 6
    ) -> list[dict[str, Any]]:
        return self.get_analyst_estimates_detailed(symbol, period=period, limit=limit)["rows"]

    def get_income_statement(
        self, symbol: str, *, period: str = "annual", limit: int = 6
    ) -> list[dict[str, Any]]:
        return self._statement("income-statement", symbol, period=period, limit=limit)

    def get_balance_sheet(
        self, symbol: str, *, period: str = "annual", limit: int = 6
    ) -> list[dict[str, Any]]:
        return self._statement("balance-sheet-statement", symbol, period=period, limit=limit)

    def get_cash_flow(
        self, symbol: str, *, period: str = "annual", limit: int = 6
    ) -> list[dict[str, Any]]:
        return self._statement("cash-flow-statement", symbol, period=period, limit=limit)

    def _statement(
        self, endpoint: str, symbol: str, *, period: str, limit: int
    ) -> list[dict[str, Any]]:
        data = self._stable_then_v3(
            endpoint,
            {"symbol": symbol, "period": period, "limit": int(limit)},
            v3_endpoint=f"{endpoint}/{symbol}",
            v3_params={"period": period, "limit": int(limit)},
            ttl_seconds=self.cache_policy.statements_ttl_seconds,
            allow_empty=True,
        )
        return [dict(row) for row in data] if isinstance(data, list) else []

    def get_key_metrics_ttm(self, symbol: str) -> list[dict[str, Any]]:
        data = self._stable_then_v3(
            "key-metrics-ttm",
            {"symbol": symbol},
            v3_endpoint=f"key-metrics-ttm/{symbol}",
            v3_params={},
            ttl_seconds=self.cache_policy.statements_ttl_seconds,
            allow_empty=True,
        )
        if isinstance(data, Mapping):
            data = [data]
        return [dict(row) for row in data] if isinstance(data, list) else []

    def get_ratios_ttm(self, symbol: str) -> list[dict[str, Any]]:
        data = self._stable_then_v3(
            "ratios-ttm",
            {"symbol": symbol},
            v3_endpoint=f"ratios-ttm/{symbol}",
            v3_params={},
            ttl_seconds=self.cache_policy.statements_ttl_seconds,
            allow_empty=True,
        )
        if isinstance(data, Mapping):
            data = [data]
        return [dict(row) for row in data] if isinstance(data, list) else []

    def get_profile(self, symbol: str) -> dict[str, Any] | None:
        data = self._stable_then_v3(
            "profile",
            {"symbol": symbol},
            v3_endpoint=f"profile/{symbol}",
            v3_params={},
            ttl_seconds=self.cache_policy.statements_ttl_seconds,
            allow_empty=True,
        )
        if isinstance(data, Mapping):
            return dict(data)
        if isinstance(data, list) and data and isinstance(data[0], Mapping):
            return dict(data[0])
        return None

    def get_stock_peers(self, symbol: str) -> list[str]:
        data = self._stable_then_v3(
            "stock-peers",
            {"symbol": symbol},
            v3_endpoint="stock_peers",
            v3_params={"symbol": symbol},
            ttl_seconds=self.cache_policy.statements_ttl_seconds,
            allow_empty=True,
        )
        if isinstance(data, Mapping):
            peers = data.get("peersList") or data.get("peers") or []
            return [str(value).upper() for value in peers if str(value).strip()]
        if isinstance(data, list):
            if data and isinstance(data[0], Mapping):
                peers = data[0].get("peersList") or data[0].get("peers") or []
                return [str(value).upper() for value in peers if str(value).strip()]
            return [str(value).upper() for value in data if isinstance(value, str)]
        return []

    @staticmethod
    def _capability_cache_key(url: str) -> str:
        return f"capability:{url}"

    def _capability_ttl_seconds(self) -> int:
        return self.CAPABILITY_CACHE_TTL_DAYS * 86_400

    def _get_cached_capability(self, url: str) -> dict[str, Any] | None:
        payload = self.cache.get(self._capability_cache_key(url), self._capability_ttl_seconds())
        return dict(payload) if isinstance(payload, Mapping) else None

    def _put_cached_capability(self, url: str, status_code: int) -> None:
        payload = {
            "endpoint": url,
            "status": status_code,
            "checked_at": datetime.now(timezone.utc).isoformat(),
            "ttl_days": self.CAPABILITY_CACHE_TTL_DAYS,
        }
        self.cache.put(self._capability_cache_key(url), payload)

    def get_bulk_dataset(self, endpoint: str, **params: Any) -> list[dict[str, Any]]:
        """Fetch a stable bulk endpoint; return an empty list when unavailable.

        Endpoint names remain configuration-driven because FMP plan access and
        stable endpoint naming can vary. Callers must record an unavailable
        endpoint and use the bounded per-symbol fallback rather than invent data.

        A 402/403 response is remembered in the persistent SQLite cache as an
        endpoint "capability" (plan access, not data). Later client instances
        pointed at the same cache path skip the HTTP call entirely for a
        capability entry that is still fresh (``CAPABILITY_CACHE_TTL_DAYS``),
        so a known-unavailable bulk endpoint never spends provider budget
        again within the TTL window. Set ``respect_capability_cache=False`` on
        construction to re-probe every endpoint unconditionally.
        """
        url = f"{self.STABLE_URL}/{endpoint.lstrip('/')}"
        if self.respect_capability_cache:
            cached = self._get_cached_capability(url)
            if (
                cached is not None
                and cached.get("status") in self.CAPABILITY_DISABLING_STATUS_CODES
            ):
                self.capability_cache_hits += 1
                self._disabled_endpoints.add(url)
                return []
        failure_count_before = len(self.failures)
        data = self._request_json(
            url,
            params,
            ttl_seconds=self.cache_policy.statements_ttl_seconds,
            allow_empty=True,
            quiet=True,
        )
        if self.respect_capability_cache and len(self.failures) > failure_count_before:
            last_failure = self.failures[-1]
            status_code = last_failure.get("status_code")
            if (
                last_failure.get("endpoint") == url
                and status_code in self.CAPABILITY_DISABLING_STATUS_CODES
            ):
                self._put_cached_capability(url, status_code)
        return [dict(row) for row in data] if isinstance(data, list) else []

    def diagnostics(self) -> dict[str, Any]:
        return {
            "api_calls_made": self.api_calls_made,
            "max_api_calls": self.max_api_calls,
            "cache_hits": self.cache_hits,
            "failure_count": len(self.failures),
            "failure_samples": [
                {**item, "endpoint": _redact_key(item.get("endpoint", ""))}
                for item in self.failures[:20]
            ],
            "disabled_endpoint_count": len(self._disabled_endpoints),
            "capability_cache_hits": self.capability_cache_hits,
            "remaining_calls": self.remaining_calls,
            "offline": self.offline,
        }
