#!/usr/bin/env python3
"""Generate docs/{en,ja}/workflows.md from workflows/*.yaml manifests.

Idempotent — same input produces byte-identical output. Run via:

    python3 scripts/generate_workflow_docs.py
    python3 scripts/generate_workflow_docs.py --lang en --output docs/en/workflows.md
    python3 scripts/generate_workflow_docs.py --check   # CI: fail if regenerated output differs

The manifests in workflows/ are the canonical source. This generator is a
read-only consumer; never edit the generated docs by hand.
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Localized labels
# ---------------------------------------------------------------------------

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "page_title": "Workflows",
        "page_intro": (
            "Operational workflow manifests for the solo-trader OS. Each workflow names "
            "the exact skills, decision gates, and artifacts in order. Manifests in "
            "[`workflows/`](https://github.com/tradermonty/claude-trading-skills/tree/main/workflows) "
            "are the canonical definition; this page is auto-generated from them."
        ),
        "auto_generated_note": (
            "This page is auto-generated by `scripts/generate_workflow_docs.py`. "
            "Do not edit by hand."
        ),
        "summary_table_title": "Available workflows",
        "col_workflow": "Workflow",
        "col_cadence": "Cadence",
        "col_minutes": "Est. min",
        "col_api": "API profile",
        "col_difficulty": "Difficulty",
        "when_to_run": "When to run",
        "when_not_to_run": "When NOT to run",
        "required_skills": "Required skills",
        "optional_skills": "Optional skills",
        "prerequisite_workflows": "Prerequisite workflows (informational)",
        "prerequisite_artifact": "expects",
        "artifacts": "Artifacts",
        "col_artifact": "Artifact",
        "col_produced_by": "Produced by step",
        "col_required": "Required",
        "col_downstream": "Downstream hints",
        "steps": "Steps",
        "step_label": "Step",
        "step_optional": "(optional)",
        "step_decision_gate": "(decision gate)",
        "step_consumes": "consumes",
        "step_produces": "produces",
        "step_decision_question": "Decision",
        "manual_review": "Manual review",
        "journal_destination": "Journal destination",
        "final_outputs": "Final outputs",
        "yes": "yes",
        "no": "no",
        "none": "(none)",
    },
    "ja": {
        "page_title": "ワークフロー",
        "page_intro": (
            "個人トレーダー OS の運用ワークフロー manifest 群です。各ワークフローは"
            "使用するスキル・判断ゲート・artifact の流れを順番通りに記述しています。"
            "[`workflows/`](https://github.com/tradermonty/claude-trading-skills/tree/main/workflows) "
            "以下の manifest が正本で、本ページはそこから自動生成されます。\n\n"
            "**翻訳方針:** 本ページは見出しラベルのみ日本語化しています。"
            "manifest 本文（`when_to_run` / `decision_question` / `manual_review` 等）は"
            "英語正本をそのまま表示します。本文の日本語化は将来の対応予定です（manifest 側に "
            "`*_ja` フィールドを追加するか、別のローカライズ層を設ける方向で検討中）。"
        ),
        "auto_generated_note": (
            "このページは `scripts/generate_workflow_docs.py` によって自動生成されます。"
            "手動編集しないでください。"
        ),
        "summary_table_title": "ワークフロー一覧",
        "col_workflow": "ワークフロー",
        "col_cadence": "頻度",
        "col_minutes": "目安(分)",
        "col_api": "API プロファイル",
        "col_difficulty": "難易度",
        "when_to_run": "実行タイミング",
        "when_not_to_run": "実行してはいけないとき",
        "required_skills": "必須スキル",
        "optional_skills": "任意スキル",
        "prerequisite_workflows": "前提ワークフロー（informational）",
        "prerequisite_artifact": "が期待する artifact",
        "artifacts": "artifact 一覧",
        "col_artifact": "Artifact",
        "col_produced_by": "生成ステップ",
        "col_required": "必須",
        "col_downstream": "下流ヒント",
        "steps": "ステップ",
        "step_label": "ステップ",
        "step_optional": "（任意）",
        "step_decision_gate": "（判断ゲート）",
        "step_consumes": "consumes",
        "step_produces": "produces",
        "step_decision_question": "判断",
        "manual_review": "手動レビュー",
        "journal_destination": "Journal 出力先",
        "final_outputs": "最終出力",
        "yes": "あり",
        "no": "なし",
        "none": "（なし）",
    },
}


JEKYLL_FRONTMATTER = {
    "en": """---
layout: default
title: Workflows
parent: English
nav_order: 4
lang_peer: /ja/workflows/
permalink: /en/workflows/
---
""",
    "ja": """---
layout: default
title: ワークフロー
parent: 日本語
nav_order: 4
lang_peer: /en/workflows/
permalink: /ja/workflows/
---
""",
}


# ---------------------------------------------------------------------------
# Workflow loading
# ---------------------------------------------------------------------------


def load_workflows(workflows_dir: Path) -> list[dict[str, Any]]:
    """Load every workflows/*.yaml as a sorted list of dicts."""
    out = []
    for path in sorted(workflows_dir.glob("*.yaml")):
        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if isinstance(data, dict) and data.get("id"):
            out.append(data)
    return out


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def _wrap(text: str | None) -> str:
    if not text:
        return ""
    # Collapse YAML folded-scalar multiline into single line
    return " ".join(text.split())


def _render_summary_table(workflows: list[dict], labels: dict[str, str]) -> str:
    buf = io.StringIO()
    buf.write(f"## {labels['summary_table_title']}\n\n")
    buf.write(
        f"| {labels['col_workflow']} | {labels['col_cadence']} | {labels['col_minutes']} | "
        f"{labels['col_api']} | {labels['col_difficulty']} |\n"
    )
    buf.write("|---|---|---|---|---|\n")
    for wf in workflows:
        wf_id = wf["id"]
        anchor = f"#{wf_id}"
        display_name = wf.get("display_name", wf_id)
        buf.write(
            f"| [`{wf_id}`]({anchor}) — {display_name} "
            f"| {wf.get('cadence', '')} "
            f"| {wf.get('estimated_minutes', '')} "
            f"| {wf.get('api_profile', '')} "
            f"| {wf.get('difficulty', '')} |\n"
        )
    buf.write("\n")
    return buf.getvalue()


def _render_skill_list(skills: list[str], labels: dict[str, str], heading: str) -> str:
    if not skills:
        return f"**{heading}:** {labels['none']}\n\n"
    items = ", ".join(f"`{s}`" for s in skills)
    return f"**{heading}:** {items}\n\n"


def _render_prerequisite_workflows(prereqs: list[dict], labels: dict[str, str]) -> str:
    if not prereqs:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['prerequisite_workflows']}:**\n\n")
    for p in prereqs:
        wf = p.get("id", "?")
        artifact = p.get("artifact", "?")
        rationale = _wrap(p.get("rationale", ""))
        buf.write(f"- `{wf}` {labels['prerequisite_artifact']} `{artifact}`")
        if rationale:
            buf.write(f" — {rationale}")
        buf.write("\n")
    buf.write("\n")
    return buf.getvalue()


def _render_artifacts(artifacts: list[dict], labels: dict[str, str]) -> str:
    if not artifacts:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['artifacts']}:**\n\n")
    buf.write(
        f"| {labels['col_artifact']} | {labels['col_produced_by']} | "
        f"{labels['col_required']} | {labels['col_downstream']} |\n"
    )
    buf.write("|---|---|---|---|\n")
    for art in artifacts:
        art_id = art.get("id", "")
        produced_by = art.get("produced_by_step", "")
        required = labels["yes"] if art.get("required", False) else labels["no"]
        downstream = art.get("downstream_hints") or []
        downstream_str = ", ".join(f"`{w}`" for w in downstream) if downstream else "—"
        buf.write(f"| `{art_id}` | {produced_by} | {required} | {downstream_str} |\n")
    buf.write("\n")
    return buf.getvalue()


def _render_step(step: dict, labels: dict[str, str]) -> str:
    buf = io.StringIO()
    step_num = step.get("step", "?")
    name = step.get("name", "")
    skill = step.get("skill", "?")
    flags = []
    if step.get("optional"):
        flags.append(labels["step_optional"])
    if step.get("decision_gate"):
        flags.append(labels["step_decision_gate"])
    flag_str = f" {' '.join(flags)}" if flags else ""

    buf.write(f"**{labels['step_label']} {step_num}: {name}**{flag_str} → `{skill}`\n\n")

    consumes = step.get("consumes") or []
    produces = step.get("produces") or []
    if consumes:
        buf.write(f"- {labels['step_consumes']}: " + ", ".join(f"`{c}`" for c in consumes) + "\n")
    if produces:
        buf.write(f"- {labels['step_produces']}: " + ", ".join(f"`{p}`" for p in produces) + "\n")
    if step.get("decision_gate"):
        q = _wrap(step.get("decision_question", ""))
        if q:
            buf.write(f"- **{labels['step_decision_question']}:** {q}\n")

    buf.write("\n")
    return buf.getvalue()


def _render_manual_review(items: list[str] | None, labels: dict[str, str]) -> str:
    if not items:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['manual_review']}:**\n\n")
    for item in items:
        buf.write(f"- {item}\n")
    buf.write("\n")
    return buf.getvalue()


def _render_final_outputs(items: list[dict] | None, labels: dict[str, str]) -> str:
    if not items:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['final_outputs']}:**\n\n")
    for item in items:
        if isinstance(item, dict):
            iid = item.get("id", "")
            desc = item.get("description", "")
            buf.write(f"- `{iid}` — {desc}\n" if desc else f"- `{iid}`\n")
        else:
            buf.write(f"- `{item}`\n")
    buf.write("\n")
    return buf.getvalue()


def render_workflow_section(wf: dict, labels: dict[str, str]) -> str:
    buf = io.StringIO()
    wf_id = wf["id"]
    display_name = wf.get("display_name", wf_id)

    buf.write(f"## {display_name} {{#{wf_id}}}\n\n")
    buf.write(
        f"**`{wf_id}`** · {wf.get('cadence', '')} · "
        f"~{wf.get('estimated_minutes', '?')} min · "
        f"{wf.get('api_profile', '')} · {wf.get('difficulty', '')}\n\n"
    )

    when_to = _wrap(wf.get("when_to_run"))
    when_not = _wrap(wf.get("when_not_to_run"))
    if when_to:
        buf.write(f"**{labels['when_to_run']}:** {when_to}\n\n")
    if when_not:
        buf.write(f"**{labels['when_not_to_run']}:** {when_not}\n\n")

    buf.write(
        _render_skill_list(wf.get("required_skills") or [], labels, labels["required_skills"])
    )
    buf.write(
        _render_skill_list(wf.get("optional_skills") or [], labels, labels["optional_skills"])
    )
    buf.write(_render_prerequisite_workflows(wf.get("prerequisite_workflows") or [], labels))
    buf.write(_render_artifacts(wf.get("artifacts") or [], labels))

    steps = wf.get("steps") or []
    if steps:
        buf.write(f"**{labels['steps']}:**\n\n")
        for step in steps:
            buf.write(_render_step(step, labels))

    buf.write(_render_manual_review(wf.get("manual_review"), labels))
    buf.write(_render_final_outputs(wf.get("final_outputs"), labels))

    journal = wf.get("journal_destination")
    if journal:
        buf.write(f"**{labels['journal_destination']}:** `{journal}`\n\n")

    buf.write("---\n\n")
    return buf.getvalue()


def render_page(workflows: list[dict], lang: str) -> str:
    labels = LABELS[lang]
    buf = io.StringIO()
    buf.write(JEKYLL_FRONTMATTER[lang])
    buf.write(f"\n# {labels['page_title']}\n")
    buf.write("{: .no_toc }\n\n")
    buf.write(f"> _{labels['auto_generated_note']}_\n\n")
    buf.write(f"{labels['page_intro']}\n\n")
    buf.write("---\n\n")
    buf.write(_render_summary_table(workflows, labels))
    buf.write("---\n\n")
    for wf in workflows:
        buf.write(render_workflow_section(wf, labels))
    # Normalize trailing newlines to a single \n so generator output stays
    # in lockstep with the end-of-file-fixer pre-commit hook. Otherwise
    # --check would always drift after the fixer trims the page.
    return buf.getvalue().rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def default_output_path(project_root: Path, lang: str) -> Path:
    return project_root / "docs" / lang / "workflows.md"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate docs/{en,ja}/workflows.md from workflows/*.yaml manifests."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Path to the repository root (default: cwd)",
    )
    parser.add_argument(
        "--lang",
        choices=["en", "ja", "all"],
        default="all",
        help="Which language to generate (default: all)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Override output path (only valid with --lang en or --lang ja)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare regenerated output against on-disk files; exit non-zero if they differ.",
    )
    args = parser.parse_args(argv)

    if args.output and args.lang == "all":
        print("--output requires --lang en or --lang ja, not all", file=sys.stderr)
        return 2

    workflows_dir = args.project_root / "workflows"
    if not workflows_dir.is_dir():
        print(f"ERROR: {workflows_dir} not found", file=sys.stderr)
        return 1

    workflows = load_workflows(workflows_dir)
    if not workflows:
        print(f"ERROR: no workflow manifests found under {workflows_dir}", file=sys.stderr)
        return 1

    langs = ["en", "ja"] if args.lang == "all" else [args.lang]
    drift = False

    for lang in langs:
        rendered = render_page(workflows, lang)
        target = args.output or default_output_path(args.project_root, lang)

        if args.check:
            if not target.is_file():
                print(f"DRIFT: {target} does not exist", file=sys.stderr)
                drift = True
                continue
            existing = target.read_text(encoding="utf-8")
            if existing != rendered:
                print(f"DRIFT: {target} differs from regenerated output", file=sys.stderr)
                drift = True
            else:
                print(f"OK: {target} matches", file=sys.stderr)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered, encoding="utf-8")
            print(f"Wrote {target} ({len(workflows)} workflows)", file=sys.stderr)

    return 1 if (args.check and drift) else 0


if __name__ == "__main__":
    raise SystemExit(main())
