#!/usr/bin/env python3
"""Generate and validate the shared exchange-calendar runtime consumers."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = REPO_ROOT / "config" / "market-calendar-dependency.yaml"
SOURCE_PATH = REPO_ROOT / "scripts" / "market_calendar" / "market_calendar.py"
TEST_TEMPLATE_PATH = (
    REPO_ROOT / "scripts" / "market_calendar" / "test_market_calendar_contract.py.tmpl"
)
CONSUMER_INVENTORY_PATH = REPO_ROOT / "scripts" / "market_calendar" / "consumers.txt"
BANNER = (
    "# GENERATED by scripts/generate_market_calendar.py — do not edit.\n"
    "# Source of truth: scripts/market_calendar/ and config/market-calendar-dependency.yaml.\n"
)


def load_config() -> dict:
    data = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or data.get("schema_version") != 1:
        raise ValueError("market-calendar dependency config must have schema_version: 1")
    requirement = data.get("requirement")
    consumers = data.get("consumers")
    mirrors = data.get("example_mirrors")
    if not isinstance(requirement, str) or "==" not in requirement:
        raise ValueError("market calendar requirement must be an exact pin")
    if not isinstance(consumers, list) or not consumers or len(consumers) != len(set(consumers)):
        raise ValueError("market calendar consumers must be a unique non-empty list")
    if not isinstance(mirrors, list) or len(mirrors) != len(set(mirrors)):
        raise ValueError("market calendar example mirrors must be a unique list")
    additional = data.get("additional_requirements", {})
    if not isinstance(additional, dict) or not set(additional).issubset(consumers):
        raise ValueError("additional requirements must be keyed by calendar consumers")
    for skill, requirements in additional.items():
        if (
            not isinstance(requirements, list)
            or not all(isinstance(item, str) and item for item in requirements)
            or len(requirements) != len(set(requirements))
        ):
            raise ValueError(f"additional requirements for {skill} must be unique strings")
    return data


def _requirements_text(requirement: str, additional: list[str] | None = None) -> str:
    requirements = [requirement, *(additional or [])]
    return BANNER + "\n".join(requirements) + "\n"


def targets(config: dict) -> list[tuple[Path, str]]:
    module = BANNER + SOURCE_PATH.read_text(encoding="utf-8")
    tests = BANNER + TEST_TEMPLATE_PATH.read_text(encoding="utf-8")
    rendered: list[tuple[Path, str]] = [
        (CONSUMER_INVENTORY_PATH, "".join(f"{skill}\n" for skill in config["consumers"]))
    ]
    additional = config.get("additional_requirements", {})
    for skill in config["consumers"]:
        skill_dir = REPO_ROOT / "skills" / skill
        requirement = _requirements_text(config["requirement"], additional.get(skill, []))
        rendered.extend(
            [
                (skill_dir / "scripts" / "_market_calendar.py", module),
                (skill_dir / "scripts" / "tests" / "test_market_calendar_contract.py", tests),
                (skill_dir / "requirements.txt", requirement),
            ]
        )
    canonical_market_utils = (
        REPO_ROOT / "skills" / "market-environment-analysis" / "scripts" / "market_utils.py"
    ).read_text(encoding="utf-8")
    for relative in config["example_mirrors"]:
        mirror = REPO_ROOT / relative
        requirement = _requirements_text(config["requirement"])
        rendered.extend(
            [
                (mirror / "scripts" / "_market_calendar.py", module),
                (mirror / "scripts" / "market_utils.py", canonical_market_utils),
                (mirror / "requirements.txt", requirement),
            ]
        )
    return rendered


def _parse_toml_list(path: Path, section: str, key: str) -> list[str] | None:
    lines = path.read_text(encoding="utf-8").splitlines()
    in_section = False
    collecting = False
    value_lines: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            in_section = stripped == f"[{section}]"
            collecting = False
            value_lines = []
            continue
        if not in_section:
            continue
        if not collecting and stripped.startswith(f"{key} ="):
            value_lines.append(stripped.split("=", 1)[1].strip())
            collecting = True
        elif collecting:
            value_lines.append(stripped)
        if collecting and stripped.startswith("]"):
            try:
                value = ast.literal_eval("\n".join(value_lines))
            except (SyntaxError, ValueError) as exc:
                raise ValueError(f"Could not parse [{section}] {key} from {path}") from exc
            if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
                raise ValueError(f"[{section}] {key} must be a list of strings")
            return value
    return None


def _requirement_name(requirement: str) -> str:
    """Return a normalized distribution name from a PEP 508-style requirement."""
    name = re.split(r"[\s<>=!~;\[]", requirement, maxsplit=1)[0]
    return name.lower().replace("_", "-")


def _python_dict_keys(path: Path, variable: str) -> set[str] | None:
    """Read a literal module-level dict without importing the target module."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or target.id != variable:
            continue
        try:
            value = ast.literal_eval(node.value)
        except (TypeError, ValueError):
            return None
        if isinstance(value, dict) and all(isinstance(key, str) for key in value):
            return set(value)
        return None
    return None


def validate_integrations(config: dict) -> list[str]:
    errors: list[str] = []
    requirement = config["requirement"]
    package_name = _requirement_name(requirement)
    pyproject = REPO_ROOT / "pyproject.toml"
    extra = _parse_toml_list(pyproject, "project.optional-dependencies", config["optional_extra"])
    if extra != [requirement]:
        errors.append(
            f"pyproject optional extra {config['optional_extra']!r} must equal [{requirement!r}]"
        )
    for key in ("dependencies", "dev"):
        section = "project" if key == "dependencies" else "project.optional-dependencies"
        values = _parse_toml_list(pyproject, section, key) or []
        if any(_requirement_name(item) == package_name for item in values):
            errors.append(f"{package_name} must not leak into [{section}] {key}")

    policy = yaml.safe_load((REPO_ROOT / "config" / "ci-test-policy.yaml").read_text())
    matrix = policy.get("matrix", {})
    consumers = set(config["consumers"])
    for skill in consumers:
        requirements = matrix.get(skill, {}).get("requirements", [])
        matches = [item for item in requirements if item.startswith(package_name)]
        if matches != [requirement]:
            errors.append(f"CI row {skill} must contain exactly {requirement}")
    for skill, row in matrix.items():
        if skill in consumers:
            continue
        if any(item.startswith(package_name) for item in row.get("requirements", [])):
            errors.append(f"Non-consumer CI row {skill} must not install {package_name}")
    smoke_consumers = _python_dict_keys(
        REPO_ROOT / "scripts" / "smoke_market_calendar.py", "CLI_PATHS"
    )
    if smoke_consumers != consumers:
        errors.append("smoke CLI_PATHS must exactly match the authority consumer inventory")
    workflow = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    if "done < scripts/market_calendar/consumers.txt" not in workflow:
        errors.append("Python 3.9 clean-room CI must read the generated consumer inventory")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when a target or pin drifts")
    args = parser.parse_args(argv)
    config = load_config()
    drift = False
    for path, content in targets(config):
        relative = path.relative_to(REPO_ROOT)
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                print(f"DRIFT: {relative}", file=sys.stderr)
                drift = True
            else:
                print(f"OK: {relative}", file=sys.stderr)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                path.write_text(content, encoding="utf-8")
                print(f"Wrote {relative}", file=sys.stderr)
            else:
                print(f"Unchanged {relative}", file=sys.stderr)
    errors = validate_integrations(config)
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    return 1 if drift or errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
