#!/usr/bin/env python3
"""Generate docs/{en,ja}/skillsets.md from skillsets/*.yaml manifests.

Idempotent — same input produces byte-identical output. Run via:

    python3 scripts/generate_skillset_docs.py
    python3 scripts/generate_skillset_docs.py --lang en --output docs/en/skillsets.md
    python3 scripts/generate_skillset_docs.py --check   # CI: fail if regenerated output differs

The manifests in skillsets/ are the canonical source. This generator is a
read-only consumer; never edit the generated docs by hand.
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Localized labels
# ---------------------------------------------------------------------------

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "page_title": "Skillsets",
        "page_intro": (
            "Purpose-specific skillset bundles for the solo-trader OS. A skillset is a "
            "category-scoped set of skills (required / recommended / optional) tied to the "
            'workflow(s) that operationalize it — the "what to install for this goal" layer. '
            "Manifests in "
            "[`skillsets/`](https://github.com/tradermonty/claude-trading-skills/tree/main/skillsets) "
            "are the canonical definition; this page is auto-generated from them."
        ),
        "auto_generated_note": (
            "This page is auto-generated by `scripts/generate_skillset_docs.py`. "
            "Do not edit by hand."
        ),
        "summary_table_title": "Available skillsets",
        "col_skillset": "Skillset",
        "col_timeframe": "Timeframe",
        "col_api": "API profile",
        "col_difficulty": "Difficulty",
        "col_related_workflows": "Related workflows",
        "when_to_use": "When to use",
        "when_not_to_use": "When NOT to use",
        "target_users": "Target users",
        "required_skills": "Required skills",
        "recommended_skills": "Recommended skills",
        "optional_skills": "Optional skills",
        "related_workflows": "Related workflows",
        "none": "(none)",
    },
    "ja": {
        "page_title": "スキルセット",
        "page_intro": (
            "個人トレーダー OS の目的別スキルセット群です。スキルセットは"
            "カテゴリ単位のスキル束（必須 / 推奨 / 任意）で、それを運用化する"
            "ワークフローに紐づきます（「この目的のために何を入れるか」の層）。"
            "[`skillsets/`](https://github.com/tradermonty/claude-trading-skills/tree/main/skillsets) "
            "以下の manifest が正本で、本ページはそこから自動生成されます。\n\n"
            "**翻訳方針:** 本ページは見出しラベルのみ日本語化しています。"
            "manifest 本文（`when_to_use` / `when_not_to_use` 等）は"
            "英語正本をそのまま表示します。本文の日本語化は将来の対応予定です（manifest 側に "
            "`*_ja` フィールドを追加するか、別のローカライズ層を設ける方向で検討中）。"
        ),
        "auto_generated_note": (
            "このページは `scripts/generate_skillset_docs.py` によって自動生成されます。"
            "手動編集しないでください。"
        ),
        "summary_table_title": "スキルセット一覧",
        "col_skillset": "スキルセット",
        "col_timeframe": "タイムフレーム",
        "col_api": "API プロファイル",
        "col_difficulty": "難易度",
        "col_related_workflows": "関連ワークフロー",
        "when_to_use": "使用するとき",
        "when_not_to_use": "使用してはいけないとき",
        "target_users": "対象ユーザー",
        "required_skills": "必須スキル",
        "recommended_skills": "推奨スキル",
        "optional_skills": "任意スキル",
        "related_workflows": "関連ワークフロー",
        "none": "（なし）",
    },
}


JEKYLL_FRONTMATTER = {
    "en": """---
layout: default
title: Skillsets
parent: English
nav_order: 5
lang_peer: /ja/skillsets/
permalink: /en/skillsets/
---
""",
    "ja": """---
layout: default
title: スキルセット
parent: 日本語
nav_order: 5
lang_peer: /en/skillsets/
permalink: /ja/skillsets/
---
""",
}


# ---------------------------------------------------------------------------
# Skillset loading
# ---------------------------------------------------------------------------


def load_skillsets(skillsets_dir: Path) -> list[dict[str, Any]]:
    """Load every skillsets/*.yaml as a sorted list of dicts."""
    out = []
    for path in sorted(skillsets_dir.glob("*.yaml")):
        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if isinstance(data, dict) and data.get("id"):
            out.append(data)
    return out


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def _wrap(text: str | None) -> str:
    if not text:
        return ""
    # Collapse YAML folded-scalar multiline into single line
    return " ".join(text.split())


def _join_codes(items: list[str] | None) -> str:
    return ", ".join(f"`{i}`" for i in (items or []))


def _render_summary_table(skillsets: list[dict], labels: dict[str, str]) -> str:
    buf = io.StringIO()
    buf.write(f"## {labels['summary_table_title']}\n\n")
    buf.write(
        f"| {labels['col_skillset']} | {labels['col_timeframe']} | "
        f"{labels['col_api']} | {labels['col_difficulty']} | "
        f"{labels['col_related_workflows']} |\n"
    )
    buf.write("|---|---|---|---|---|\n")
    for ss in skillsets:
        ss_id = ss["id"]
        anchor = f"#{ss_id}"
        display_name = ss.get("display_name", ss_id)
        related = _join_codes(ss.get("related_workflows")) or labels["none"]
        buf.write(
            f"| [`{ss_id}`]({anchor}) — {display_name} "
            f"| {ss.get('timeframe', '')} "
            f"| {ss.get('api_profile', '')} "
            f"| {ss.get('difficulty', '')} "
            f"| {related} |\n"
        )
    buf.write("\n")
    return buf.getvalue()


def _render_skill_list(skills: list[str], labels: dict[str, str], heading: str) -> str:
    if not skills:
        return f"**{heading}:** {labels['none']}\n\n"
    items = ", ".join(f"`{s}`" for s in skills)
    return f"**{heading}:** {items}\n\n"


def render_skillset_section(ss: dict, labels: dict[str, str]) -> str:
    buf = io.StringIO()
    ss_id = ss["id"]
    display_name = ss.get("display_name", ss_id)

    buf.write(f"## {display_name} {{#{ss_id}}}\n\n")
    buf.write(
        f"**`{ss_id}`** · {ss.get('timeframe', '')} · "
        f"{ss.get('api_profile', '')} · {ss.get('difficulty', '')}\n\n"
    )

    when_to = _wrap(ss.get("when_to_use"))
    when_not = _wrap(ss.get("when_not_to_use"))
    if when_to:
        buf.write(f"**{labels['when_to_use']}:** {when_to}\n\n")
    if when_not:
        buf.write(f"**{labels['when_not_to_use']}:** {when_not}\n\n")

    target_users = ss.get("target_users") or []
    if target_users:
        buf.write(f"**{labels['target_users']}:** {_join_codes(target_users)}\n\n")

    buf.write(
        _render_skill_list(ss.get("required_skills") or [], labels, labels["required_skills"])
    )
    buf.write(
        _render_skill_list(ss.get("recommended_skills") or [], labels, labels["recommended_skills"])
    )
    buf.write(
        _render_skill_list(ss.get("optional_skills") or [], labels, labels["optional_skills"])
    )

    related = ss.get("related_workflows") or []
    if related:
        buf.write(f"**{labels['related_workflows']}:** {_join_codes(related)}\n\n")

    buf.write("---\n\n")
    return buf.getvalue()


def render_page(skillsets: list[dict], lang: str) -> str:
    labels = LABELS[lang]
    buf = io.StringIO()
    buf.write(JEKYLL_FRONTMATTER[lang])
    buf.write(f"\n# {labels['page_title']}\n")
    buf.write("{: .no_toc }\n\n")
    buf.write(f"> _{labels['auto_generated_note']}_\n\n")
    buf.write(f"{labels['page_intro']}\n\n")
    buf.write("---\n\n")
    buf.write(_render_summary_table(skillsets, labels))
    buf.write("---\n\n")
    for ss in skillsets:
        buf.write(render_skillset_section(ss, labels))
    # Normalize trailing newlines to a single \n so generator output stays
    # in lockstep with the end-of-file-fixer pre-commit hook. Otherwise
    # --check would always drift after the fixer trims the page.
    return buf.getvalue().rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def default_output_path(project_root: Path, lang: str) -> Path:
    return project_root / "docs" / lang / "skillsets.md"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate docs/{en,ja}/skillsets.md from skillsets/*.yaml manifests."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Path to the repository root (default: cwd)",
    )
    parser.add_argument(
        "--lang",
        choices=["en", "ja", "all"],
        default="all",
        help="Which language to generate (default: all)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Override output path (only valid with --lang en or --lang ja)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare regenerated output against on-disk files; exit non-zero if they differ.",
    )
    args = parser.parse_args(argv)

    if args.output and args.lang == "all":
        print("--output requires --lang en or --lang ja, not all", file=sys.stderr)
        return 2

    skillsets_dir = args.project_root / "skillsets"
    if not skillsets_dir.is_dir():
        print(f"ERROR: {skillsets_dir} not found", file=sys.stderr)
        return 1

    skillsets = load_skillsets(skillsets_dir)
    if not skillsets:
        print(f"ERROR: no skillset manifests found under {skillsets_dir}", file=sys.stderr)
        return 1

    langs = ["en", "ja"] if args.lang == "all" else [args.lang]
    drift = False

    for lang in langs:
        rendered = render_page(skillsets, lang)
        target = args.output or default_output_path(args.project_root, lang)

        if args.check:
            if not target.is_file():
                print(f"DRIFT: {target} does not exist", file=sys.stderr)
                drift = True
                continue
            existing = target.read_text(encoding="utf-8")
            if existing != rendered:
                print(f"DRIFT: {target} differs from regenerated output", file=sys.stderr)
                drift = True
            else:
                print(f"OK: {target} matches", file=sys.stderr)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered, encoding="utf-8")
            print(f"Wrote {target} ({len(skillsets)} skillsets)", file=sys.stderr)

    return 1 if (args.check and drift) else 0


if __name__ == "__main__":
    raise SystemExit(main())
